# spring.application.name=Timesheet

server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: unsafe_client
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak  # Указываем провайдера
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/master
            authorization-uri: http://localhost:8080/realms/master/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/master/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs


  application:
    name: timesheet-rest
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false
eureka:
  client:
    enabled: false
application:
  logging:
    level: WARN
    enabled: true
    printArgs: true
exception:
  logging:
    enabled: false
    noRecoverFor:
      - java.lang.NullPointerException
      - java.lang.IllegalArgumentException




